//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MIO.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

/**
 * Helper class for marshaling/unmarshaling ArcList.
 **/
public final class ArcListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, ArcInfo[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                ArcInfo.ice_write(ostr, v[i0]);
            }
        }
    }

    public static ArcInfo[] read(com.zeroc.Ice.InputStream istr)
    {
        final ArcInfo[] v;
        final int len0 = istr.readAndCheckSeqSize(21);
        v = new ArcInfo[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = ArcInfo.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ArcInfo[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, ArcInfo[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ArcListHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<ArcInfo[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            ArcInfo[] v;
            v = ArcListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
