//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MIO.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public interface Master extends com.zeroc.Ice.Object
{
    void registerWorker(WorkerPrx worker, com.zeroc.Ice.Current current);

    void unregisterWorker(int workerId, com.zeroc.Ice.Current current);

    int getWorkerCount(com.zeroc.Ice.Current current);

    GlobalResult processDatagrams(SpeedDatagram[] datagrams, int numTasks, com.zeroc.Ice.Current current);

    SpeedDatagram[] generateTestDatagrams(int count, ArcInfo[] arcs, com.zeroc.Ice.Current current);

    SpeedDatagram[] loadDatagramsFromCSV(String filePath, int maxCount, com.zeroc.Ice.Current current);

    String runBenchmarkWithRealData(String csvPath, com.zeroc.Ice.Current current);

    String runBenchmark(ArcInfo[] arcs, com.zeroc.Ice.Current current);

    SpeedDatagram[] getDatagramsFromServer(int count, com.zeroc.Ice.Current current);

    int getTotalDatagramsCount(com.zeroc.Ice.Current current);

    String runBenchmarkWithRealDataFromServer(com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::MIO::Master"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::MIO::Master";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_registerWorker(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        WorkerPrx iceP_worker;
        iceP_worker = WorkerPrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        obj.registerWorker(iceP_worker, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_unregisterWorker(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_workerId;
        iceP_workerId = istr.readInt();
        inS.endReadParams();
        obj.unregisterWorker(iceP_workerId, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getWorkerCount(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        int ret = obj.getWorkerCount(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeInt(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_processDatagrams(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        SpeedDatagram[] iceP_datagrams;
        int iceP_numTasks;
        iceP_datagrams = DatagramListHelper.read(istr);
        iceP_numTasks = istr.readInt();
        inS.endReadParams();
        GlobalResult ret = obj.processDatagrams(iceP_datagrams, iceP_numTasks, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        GlobalResult.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_generateTestDatagrams(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_count;
        ArcInfo[] iceP_arcs;
        iceP_count = istr.readInt();
        iceP_arcs = ArcListHelper.read(istr);
        inS.endReadParams();
        SpeedDatagram[] ret = obj.generateTestDatagrams(iceP_count, iceP_arcs, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        DatagramListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_loadDatagramsFromCSV(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_filePath;
        int iceP_maxCount;
        iceP_filePath = istr.readString();
        iceP_maxCount = istr.readInt();
        inS.endReadParams();
        SpeedDatagram[] ret = obj.loadDatagramsFromCSV(iceP_filePath, iceP_maxCount, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        DatagramListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_runBenchmarkWithRealData(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_csvPath;
        iceP_csvPath = istr.readString();
        inS.endReadParams();
        String ret = obj.runBenchmarkWithRealData(iceP_csvPath, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_runBenchmark(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        ArcInfo[] iceP_arcs;
        iceP_arcs = ArcListHelper.read(istr);
        inS.endReadParams();
        String ret = obj.runBenchmark(iceP_arcs, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getDatagramsFromServer(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_count;
        iceP_count = istr.readInt();
        inS.endReadParams();
        SpeedDatagram[] ret = obj.getDatagramsFromServer(iceP_count, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        DatagramListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getTotalDatagramsCount(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        int ret = obj.getTotalDatagramsCount(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeInt(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_runBenchmarkWithRealDataFromServer(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String ret = obj.runBenchmarkWithRealDataFromServer(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "generateTestDatagrams",
        "getDatagramsFromServer",
        "getTotalDatagramsCount",
        "getWorkerCount",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "loadDatagramsFromCSV",
        "processDatagrams",
        "registerWorker",
        "runBenchmark",
        "runBenchmarkWithRealData",
        "runBenchmarkWithRealDataFromServer",
        "unregisterWorker"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_generateTestDatagrams(this, in, current);
            }
            case 1:
            {
                return _iceD_getDatagramsFromServer(this, in, current);
            }
            case 2:
            {
                return _iceD_getTotalDatagramsCount(this, in, current);
            }
            case 3:
            {
                return _iceD_getWorkerCount(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 8:
            {
                return _iceD_loadDatagramsFromCSV(this, in, current);
            }
            case 9:
            {
                return _iceD_processDatagrams(this, in, current);
            }
            case 10:
            {
                return _iceD_registerWorker(this, in, current);
            }
            case 11:
            {
                return _iceD_runBenchmark(this, in, current);
            }
            case 12:
            {
                return _iceD_runBenchmarkWithRealData(this, in, current);
            }
            case 13:
            {
                return _iceD_runBenchmarkWithRealDataFromServer(this, in, current);
            }
            case 14:
            {
                return _iceD_unregisterWorker(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
