//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MIO.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public interface MIOServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default StopInfo getStop(int stopId)
    {
        return getStop(stopId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default StopInfo getStop(int stopId, java.util.Map<String, String> context)
    {
        return _iceI_getStopAsync(stopId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<StopInfo> getStopAsync(int stopId)
    {
        return _iceI_getStopAsync(stopId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<StopInfo> getStopAsync(int stopId, java.util.Map<String, String> context)
    {
        return _iceI_getStopAsync(stopId, context, false);
    }

    /**
     * @hidden
     * @param iceP_stopId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<StopInfo> _iceI_getStopAsync(int iceP_stopId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<StopInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getStop", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_stopId);
                 }, istr -> {
                     StopInfo ret;
                     ret = StopInfo.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default StopInfo[] getAllStops()
    {
        return getAllStops(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default StopInfo[] getAllStops(java.util.Map<String, String> context)
    {
        return _iceI_getAllStopsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<StopInfo[]> getAllStopsAsync()
    {
        return _iceI_getAllStopsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<StopInfo[]> getAllStopsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getAllStopsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<StopInfo[]> _iceI_getAllStopsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<StopInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAllStops", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     StopInfo[] ret;
                     ret = StopListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default RouteInfo getRoute(int routeId)
    {
        return getRoute(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default RouteInfo getRoute(int routeId, java.util.Map<String, String> context)
    {
        return _iceI_getRouteAsync(routeId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<RouteInfo> getRouteAsync(int routeId)
    {
        return _iceI_getRouteAsync(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<RouteInfo> getRouteAsync(int routeId, java.util.Map<String, String> context)
    {
        return _iceI_getRouteAsync(routeId, context, false);
    }

    /**
     * @hidden
     * @param iceP_routeId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<RouteInfo> _iceI_getRouteAsync(int iceP_routeId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<RouteInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getRoute", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_routeId);
                 }, istr -> {
                     RouteInfo ret;
                     ret = RouteInfo.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default RouteInfo[] getAllRoutes()
    {
        return getAllRoutes(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default RouteInfo[] getAllRoutes(java.util.Map<String, String> context)
    {
        return _iceI_getAllRoutesAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<RouteInfo[]> getAllRoutesAsync()
    {
        return _iceI_getAllRoutesAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<RouteInfo[]> getAllRoutesAsync(java.util.Map<String, String> context)
    {
        return _iceI_getAllRoutesAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<RouteInfo[]> _iceI_getAllRoutesAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<RouteInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAllRoutes", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     RouteInfo[] ret;
                     ret = RouteListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default ArcInfo[] getAllArcs()
    {
        return getAllArcs(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ArcInfo[] getAllArcs(java.util.Map<String, String> context)
    {
        return _iceI_getAllArcsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ArcInfo[]> getAllArcsAsync()
    {
        return _iceI_getAllArcsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ArcInfo[]> getAllArcsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getAllArcsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ArcInfo[]> _iceI_getAllArcsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ArcInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAllArcs", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     ArcInfo[] ret;
                     ret = ArcListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default ArcInfo[] getArcsByRoute(int routeId, int orientation)
    {
        return getArcsByRoute(routeId, orientation, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ArcInfo[] getArcsByRoute(int routeId, int orientation, java.util.Map<String, String> context)
    {
        return _iceI_getArcsByRouteAsync(routeId, orientation, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ArcInfo[]> getArcsByRouteAsync(int routeId, int orientation)
    {
        return _iceI_getArcsByRouteAsync(routeId, orientation, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ArcInfo[]> getArcsByRouteAsync(int routeId, int orientation, java.util.Map<String, String> context)
    {
        return _iceI_getArcsByRouteAsync(routeId, orientation, context, false);
    }

    /**
     * @hidden
     * @param iceP_routeId -
     * @param iceP_orientation -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ArcInfo[]> _iceI_getArcsByRouteAsync(int iceP_routeId, int iceP_orientation, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ArcInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getArcsByRoute", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_routeId);
                     ostr.writeInt(iceP_orientation);
                 }, istr -> {
                     ArcInfo[] ret;
                     ret = ArcListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default String getStatistics()
    {
        return getStatistics(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getStatistics(java.util.Map<String, String> context)
    {
        return _iceI_getStatisticsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getStatisticsAsync()
    {
        return _iceI_getStatisticsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getStatisticsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getStatisticsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getStatisticsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getStatistics", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default void buildGraph()
    {
        buildGraph(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void buildGraph(java.util.Map<String, String> context)
    {
        _iceI_buildGraphAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> buildGraphAsync()
    {
        return _iceI_buildGraphAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> buildGraphAsync(java.util.Map<String, String> context)
    {
        return _iceI_buildGraphAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_buildGraphAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "buildGraph", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MIOServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), MIOServicePrx.class, _MIOServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MIOServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), MIOServicePrx.class, _MIOServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MIOServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), MIOServicePrx.class, _MIOServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MIOServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), MIOServicePrx.class, _MIOServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static MIOServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, MIOServicePrx.class, _MIOServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static MIOServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, MIOServicePrx.class, _MIOServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default MIOServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (MIOServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default MIOServicePrx ice_adapterId(String newAdapterId)
    {
        return (MIOServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default MIOServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (MIOServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default MIOServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (MIOServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default MIOServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (MIOServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default MIOServicePrx ice_connectionCached(boolean newCache)
    {
        return (MIOServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default MIOServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (MIOServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MIOServicePrx ice_secure(boolean b)
    {
        return (MIOServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default MIOServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (MIOServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MIOServicePrx ice_preferSecure(boolean b)
    {
        return (MIOServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default MIOServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (MIOServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default MIOServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (MIOServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default MIOServicePrx ice_collocationOptimized(boolean b)
    {
        return (MIOServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default MIOServicePrx ice_twoway()
    {
        return (MIOServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default MIOServicePrx ice_oneway()
    {
        return (MIOServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default MIOServicePrx ice_batchOneway()
    {
        return (MIOServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default MIOServicePrx ice_datagram()
    {
        return (MIOServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default MIOServicePrx ice_batchDatagram()
    {
        return (MIOServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default MIOServicePrx ice_compress(boolean co)
    {
        return (MIOServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default MIOServicePrx ice_timeout(int t)
    {
        return (MIOServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default MIOServicePrx ice_connectionId(String connectionId)
    {
        return (MIOServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default MIOServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (MIOServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::MIO::MIOService";
    }
}
