//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MIO.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

/**
 * Helper class for marshaling/unmarshaling PartialResultList.
 **/
public final class PartialResultListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, PartialResult[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                PartialResult.ice_write(ostr, v[i0]);
            }
        }
    }

    public static PartialResult[] read(com.zeroc.Ice.InputStream istr)
    {
        final PartialResult[] v;
        final int len0 = istr.readAndCheckSeqSize(72);
        v = new PartialResult[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = PartialResult.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<PartialResult[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, PartialResult[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            final int optSize = v == null ? 0 : v.length;
            ostr.writeSize(optSize > 254 ? optSize * 72 + 5 : optSize * 72 + 1);
            PartialResultListHelper.write(ostr, v);
        }
    }

    public static java.util.Optional<PartialResult[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            PartialResult[] v;
            v = PartialResultListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
