//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MIO.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class RouteInfo implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public int routeId;

    public String routeName;

    public String variant;

    public int orientation;

    public RouteInfo()
    {
        this.routeName = "";
        this.variant = "";
    }

    public RouteInfo(int routeId, String routeName, String variant, int orientation)
    {
        this.routeId = routeId;
        this.routeName = routeName;
        this.variant = variant;
        this.orientation = orientation;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        RouteInfo r = null;
        if(rhs instanceof RouteInfo)
        {
            r = (RouteInfo)rhs;
        }

        if(r != null)
        {
            if(this.routeId != r.routeId)
            {
                return false;
            }
            if(this.routeName != r.routeName)
            {
                if(this.routeName == null || r.routeName == null || !this.routeName.equals(r.routeName))
                {
                    return false;
                }
            }
            if(this.variant != r.variant)
            {
                if(this.variant == null || r.variant == null || !this.variant.equals(r.variant))
                {
                    return false;
                }
            }
            if(this.orientation != r.orientation)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MIO::RouteInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, routeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, routeName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, variant);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, orientation);
        return h_;
    }

    public RouteInfo clone()
    {
        RouteInfo c = null;
        try
        {
            c = (RouteInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.routeId);
        ostr.writeString(this.routeName);
        ostr.writeString(this.variant);
        ostr.writeInt(this.orientation);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.routeId = istr.readInt();
        this.routeName = istr.readString();
        this.variant = istr.readString();
        this.orientation = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, RouteInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public RouteInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        RouteInfo v = new RouteInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<RouteInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, RouteInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<RouteInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(RouteInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final RouteInfo _nullMarshalValue = new RouteInfo();

    /** @hidden */
    public static final long serialVersionUID = -249454884L;
}
