//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MIO.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class SpeedDatagram implements java.lang.Cloneable,
                                      java.io.Serializable
{
    public int arcId;

    public int fromStopId;

    public int toStopId;

    public double speed;

    public long timestamp;

    public double fromLat;

    public double fromLon;

    public double toLat;

    public double toLon;

    public SpeedDatagram()
    {
    }

    public SpeedDatagram(int arcId, int fromStopId, int toStopId, double speed, long timestamp, double fromLat, double fromLon, double toLat, double toLon)
    {
        this.arcId = arcId;
        this.fromStopId = fromStopId;
        this.toStopId = toStopId;
        this.speed = speed;
        this.timestamp = timestamp;
        this.fromLat = fromLat;
        this.fromLon = fromLon;
        this.toLat = toLat;
        this.toLon = toLon;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        SpeedDatagram r = null;
        if(rhs instanceof SpeedDatagram)
        {
            r = (SpeedDatagram)rhs;
        }

        if(r != null)
        {
            if(this.arcId != r.arcId)
            {
                return false;
            }
            if(this.fromStopId != r.fromStopId)
            {
                return false;
            }
            if(this.toStopId != r.toStopId)
            {
                return false;
            }
            if(this.speed != r.speed)
            {
                return false;
            }
            if(this.timestamp != r.timestamp)
            {
                return false;
            }
            if(this.fromLat != r.fromLat)
            {
                return false;
            }
            if(this.fromLon != r.fromLon)
            {
                return false;
            }
            if(this.toLat != r.toLat)
            {
                return false;
            }
            if(this.toLon != r.toLon)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MIO::SpeedDatagram");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, arcId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fromStopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, toStopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, speed);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fromLat);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fromLon);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, toLat);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, toLon);
        return h_;
    }

    public SpeedDatagram clone()
    {
        SpeedDatagram c = null;
        try
        {
            c = (SpeedDatagram)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.arcId);
        ostr.writeInt(this.fromStopId);
        ostr.writeInt(this.toStopId);
        ostr.writeDouble(this.speed);
        ostr.writeLong(this.timestamp);
        ostr.writeDouble(this.fromLat);
        ostr.writeDouble(this.fromLon);
        ostr.writeDouble(this.toLat);
        ostr.writeDouble(this.toLon);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.arcId = istr.readInt();
        this.fromStopId = istr.readInt();
        this.toStopId = istr.readInt();
        this.speed = istr.readDouble();
        this.timestamp = istr.readLong();
        this.fromLat = istr.readDouble();
        this.fromLon = istr.readDouble();
        this.toLat = istr.readDouble();
        this.toLon = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, SpeedDatagram v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public SpeedDatagram ice_read(com.zeroc.Ice.InputStream istr)
    {
        SpeedDatagram v = new SpeedDatagram();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<SpeedDatagram> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, SpeedDatagram v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(60);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<SpeedDatagram> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(SpeedDatagram.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final SpeedDatagram _nullMarshalValue = new SpeedDatagram();

    /** @hidden */
    public static final long serialVersionUID = 1144855728L;
}
