//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MIO.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class ArcInfo implements java.lang.Cloneable,
                                java.io.Serializable
{
    public int fromStopId;

    public int toStopId;

    public int routeId;

    public String routeName;

    public int orientation;

    public int sequenceOrder;

    public ArcInfo()
    {
        this.routeName = "";
    }

    public ArcInfo(int fromStopId, int toStopId, int routeId, String routeName, int orientation, int sequenceOrder)
    {
        this.fromStopId = fromStopId;
        this.toStopId = toStopId;
        this.routeId = routeId;
        this.routeName = routeName;
        this.orientation = orientation;
        this.sequenceOrder = sequenceOrder;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ArcInfo r = null;
        if(rhs instanceof ArcInfo)
        {
            r = (ArcInfo)rhs;
        }

        if(r != null)
        {
            if(this.fromStopId != r.fromStopId)
            {
                return false;
            }
            if(this.toStopId != r.toStopId)
            {
                return false;
            }
            if(this.routeId != r.routeId)
            {
                return false;
            }
            if(this.routeName != r.routeName)
            {
                if(this.routeName == null || r.routeName == null || !this.routeName.equals(r.routeName))
                {
                    return false;
                }
            }
            if(this.orientation != r.orientation)
            {
                return false;
            }
            if(this.sequenceOrder != r.sequenceOrder)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MIO::ArcInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fromStopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, toStopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, routeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, routeName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, orientation);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sequenceOrder);
        return h_;
    }

    public ArcInfo clone()
    {
        ArcInfo c = null;
        try
        {
            c = (ArcInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.fromStopId);
        ostr.writeInt(this.toStopId);
        ostr.writeInt(this.routeId);
        ostr.writeString(this.routeName);
        ostr.writeInt(this.orientation);
        ostr.writeInt(this.sequenceOrder);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.fromStopId = istr.readInt();
        this.toStopId = istr.readInt();
        this.routeId = istr.readInt();
        this.routeName = istr.readString();
        this.orientation = istr.readInt();
        this.sequenceOrder = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ArcInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ArcInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        ArcInfo v = new ArcInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ArcInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ArcInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ArcInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ArcInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ArcInfo _nullMarshalValue = new ArcInfo();

    /** @hidden */
    public static final long serialVersionUID = 1788328446L;
}
