//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MIO.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class GlobalResult implements java.lang.Cloneable,
                                     java.io.Serializable
{
    public int totalArcs;

    public long totalDatagrams;

    public double globalAvgSpeed;

    public long totalProcessingTimeMs;

    public int workerCount;

    public int taskCount;

    public GlobalResult()
    {
    }

    public GlobalResult(int totalArcs, long totalDatagrams, double globalAvgSpeed, long totalProcessingTimeMs, int workerCount, int taskCount)
    {
        this.totalArcs = totalArcs;
        this.totalDatagrams = totalDatagrams;
        this.globalAvgSpeed = globalAvgSpeed;
        this.totalProcessingTimeMs = totalProcessingTimeMs;
        this.workerCount = workerCount;
        this.taskCount = taskCount;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        GlobalResult r = null;
        if(rhs instanceof GlobalResult)
        {
            r = (GlobalResult)rhs;
        }

        if(r != null)
        {
            if(this.totalArcs != r.totalArcs)
            {
                return false;
            }
            if(this.totalDatagrams != r.totalDatagrams)
            {
                return false;
            }
            if(this.globalAvgSpeed != r.globalAvgSpeed)
            {
                return false;
            }
            if(this.totalProcessingTimeMs != r.totalProcessingTimeMs)
            {
                return false;
            }
            if(this.workerCount != r.workerCount)
            {
                return false;
            }
            if(this.taskCount != r.taskCount)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MIO::GlobalResult");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalArcs);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalDatagrams);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, globalAvgSpeed);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalProcessingTimeMs);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, workerCount);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskCount);
        return h_;
    }

    public GlobalResult clone()
    {
        GlobalResult c = null;
        try
        {
            c = (GlobalResult)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.totalArcs);
        ostr.writeLong(this.totalDatagrams);
        ostr.writeDouble(this.globalAvgSpeed);
        ostr.writeLong(this.totalProcessingTimeMs);
        ostr.writeInt(this.workerCount);
        ostr.writeInt(this.taskCount);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.totalArcs = istr.readInt();
        this.totalDatagrams = istr.readLong();
        this.globalAvgSpeed = istr.readDouble();
        this.totalProcessingTimeMs = istr.readLong();
        this.workerCount = istr.readInt();
        this.taskCount = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, GlobalResult v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public GlobalResult ice_read(com.zeroc.Ice.InputStream istr)
    {
        GlobalResult v = new GlobalResult();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<GlobalResult> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, GlobalResult v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(36);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<GlobalResult> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(GlobalResult.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final GlobalResult _nullMarshalValue = new GlobalResult();

    /** @hidden */
    public static final long serialVersionUID = -283801538L;
}
