//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MIO.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public interface MIOService extends com.zeroc.Ice.Object
{
    StopInfo getStop(int stopId, com.zeroc.Ice.Current current);

    StopInfo[] getAllStops(com.zeroc.Ice.Current current);

    RouteInfo getRoute(int routeId, com.zeroc.Ice.Current current);

    RouteInfo[] getAllRoutes(com.zeroc.Ice.Current current);

    ArcInfo[] getAllArcs(com.zeroc.Ice.Current current);

    ArcInfo[] getArcsByRoute(int routeId, int orientation, com.zeroc.Ice.Current current);

    String getStatistics(com.zeroc.Ice.Current current);

    void buildGraph(com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::MIO::MIOService"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::MIO::MIOService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getStop(MIOService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_stopId;
        iceP_stopId = istr.readInt();
        inS.endReadParams();
        StopInfo ret = obj.getStop(iceP_stopId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        StopInfo.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getAllStops(MIOService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        StopInfo[] ret = obj.getAllStops(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        StopListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getRoute(MIOService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_routeId;
        iceP_routeId = istr.readInt();
        inS.endReadParams();
        RouteInfo ret = obj.getRoute(iceP_routeId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        RouteInfo.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getAllRoutes(MIOService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        RouteInfo[] ret = obj.getAllRoutes(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        RouteListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getAllArcs(MIOService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        ArcInfo[] ret = obj.getAllArcs(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ArcListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getArcsByRoute(MIOService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_routeId;
        int iceP_orientation;
        iceP_routeId = istr.readInt();
        iceP_orientation = istr.readInt();
        inS.endReadParams();
        ArcInfo[] ret = obj.getArcsByRoute(iceP_routeId, iceP_orientation, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ArcListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getStatistics(MIOService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String ret = obj.getStatistics(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_buildGraph(MIOService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        obj.buildGraph(current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "buildGraph",
        "getAllArcs",
        "getAllRoutes",
        "getAllStops",
        "getArcsByRoute",
        "getRoute",
        "getStatistics",
        "getStop",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_buildGraph(this, in, current);
            }
            case 1:
            {
                return _iceD_getAllArcs(this, in, current);
            }
            case 2:
            {
                return _iceD_getAllRoutes(this, in, current);
            }
            case 3:
            {
                return _iceD_getAllStops(this, in, current);
            }
            case 4:
            {
                return _iceD_getArcsByRoute(this, in, current);
            }
            case 5:
            {
                return _iceD_getRoute(this, in, current);
            }
            case 6:
            {
                return _iceD_getStatistics(this, in, current);
            }
            case 7:
            {
                return _iceD_getStop(this, in, current);
            }
            case 8:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 9:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 10:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 11:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
