//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MIO.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class PartialResult implements java.lang.Cloneable,
                                      java.io.Serializable
{
    public int taskId;

    public int arcCount;

    public long datagramCount;

    public double sumSpeed;

    public double totalDistance;

    public double totalTime;

    public double avgSpeed;

    public long processingTimeMs;

    public double filteredSpeedSum;

    public long filteredCount;

    public PartialResult()
    {
    }

    public PartialResult(int taskId, int arcCount, long datagramCount, double sumSpeed, double totalDistance, double totalTime, double avgSpeed, long processingTimeMs, double filteredSpeedSum, long filteredCount)
    {
        this.taskId = taskId;
        this.arcCount = arcCount;
        this.datagramCount = datagramCount;
        this.sumSpeed = sumSpeed;
        this.totalDistance = totalDistance;
        this.totalTime = totalTime;
        this.avgSpeed = avgSpeed;
        this.processingTimeMs = processingTimeMs;
        this.filteredSpeedSum = filteredSpeedSum;
        this.filteredCount = filteredCount;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        PartialResult r = null;
        if(rhs instanceof PartialResult)
        {
            r = (PartialResult)rhs;
        }

        if(r != null)
        {
            if(this.taskId != r.taskId)
            {
                return false;
            }
            if(this.arcCount != r.arcCount)
            {
                return false;
            }
            if(this.datagramCount != r.datagramCount)
            {
                return false;
            }
            if(this.sumSpeed != r.sumSpeed)
            {
                return false;
            }
            if(this.totalDistance != r.totalDistance)
            {
                return false;
            }
            if(this.totalTime != r.totalTime)
            {
                return false;
            }
            if(this.avgSpeed != r.avgSpeed)
            {
                return false;
            }
            if(this.processingTimeMs != r.processingTimeMs)
            {
                return false;
            }
            if(this.filteredSpeedSum != r.filteredSpeedSum)
            {
                return false;
            }
            if(this.filteredCount != r.filteredCount)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MIO::PartialResult");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, arcCount);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, datagramCount);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sumSpeed);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalDistance);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalTime);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, avgSpeed);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, processingTimeMs);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, filteredSpeedSum);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, filteredCount);
        return h_;
    }

    public PartialResult clone()
    {
        PartialResult c = null;
        try
        {
            c = (PartialResult)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.taskId);
        ostr.writeInt(this.arcCount);
        ostr.writeLong(this.datagramCount);
        ostr.writeDouble(this.sumSpeed);
        ostr.writeDouble(this.totalDistance);
        ostr.writeDouble(this.totalTime);
        ostr.writeDouble(this.avgSpeed);
        ostr.writeLong(this.processingTimeMs);
        ostr.writeDouble(this.filteredSpeedSum);
        ostr.writeLong(this.filteredCount);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.taskId = istr.readInt();
        this.arcCount = istr.readInt();
        this.datagramCount = istr.readLong();
        this.sumSpeed = istr.readDouble();
        this.totalDistance = istr.readDouble();
        this.totalTime = istr.readDouble();
        this.avgSpeed = istr.readDouble();
        this.processingTimeMs = istr.readLong();
        this.filteredSpeedSum = istr.readDouble();
        this.filteredCount = istr.readLong();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, PartialResult v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public PartialResult ice_read(com.zeroc.Ice.InputStream istr)
    {
        PartialResult v = new PartialResult();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<PartialResult> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, PartialResult v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(72);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<PartialResult> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(PartialResult.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final PartialResult _nullMarshalValue = new PartialResult();

    /** @hidden */
    public static final long serialVersionUID = -1009307455L;
}
