//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MIO.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class StopInfo implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public int stopId;

    public String stopName;

    public double latitude;

    public double longitude;

    public StopInfo()
    {
        this.stopName = "";
    }

    public StopInfo(int stopId, String stopName, double latitude, double longitude)
    {
        this.stopId = stopId;
        this.stopName = stopName;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        StopInfo r = null;
        if(rhs instanceof StopInfo)
        {
            r = (StopInfo)rhs;
        }

        if(r != null)
        {
            if(this.stopId != r.stopId)
            {
                return false;
            }
            if(this.stopName != r.stopName)
            {
                if(this.stopName == null || r.stopName == null || !this.stopName.equals(r.stopName))
                {
                    return false;
                }
            }
            if(this.latitude != r.latitude)
            {
                return false;
            }
            if(this.longitude != r.longitude)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MIO::StopInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, stopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, stopName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, latitude);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, longitude);
        return h_;
    }

    public StopInfo clone()
    {
        StopInfo c = null;
        try
        {
            c = (StopInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.stopId);
        ostr.writeString(this.stopName);
        ostr.writeDouble(this.latitude);
        ostr.writeDouble(this.longitude);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.stopId = istr.readInt();
        this.stopName = istr.readString();
        this.latitude = istr.readDouble();
        this.longitude = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, StopInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public StopInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        StopInfo v = new StopInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<StopInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, StopInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<StopInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(StopInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final StopInfo _nullMarshalValue = new StopInfo();

    /** @hidden */
    public static final long serialVersionUID = 1908527855L;
}
