//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MIO.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

/**
 * Helper class for marshaling/unmarshaling StopList.
 **/
public final class StopListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, StopInfo[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                StopInfo.ice_write(ostr, v[i0]);
            }
        }
    }

    public static StopInfo[] read(com.zeroc.Ice.InputStream istr)
    {
        final StopInfo[] v;
        final int len0 = istr.readAndCheckSeqSize(21);
        v = new StopInfo[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = StopInfo.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<StopInfo[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, StopInfo[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            StopListHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<StopInfo[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            StopInfo[] v;
            v = StopListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
